export const columns = [
  {
    dataIndex: "name",
    key: "name",
    slots: { title: "Name" },
    width: 200,
  },
  {
    dataIndex: "age",
    key: "age",
    slots: { title: "Age" },
    width: 200,
  },
  {
    dataIndex: "address",
    key: "address",
    slots: { title: "Address" },
    width: 200,
  },
  {
    key: "tags",
    dataIndex: "tags",
    scopedSlots: { customRender: "tags" },
    slots: { title: "Tags" },
    width: 200,
  },
  {
    key: "test1",
    dataIndex: "test1",
    scopedSlots: { customRender: "test1" },
    slots: { title: "Test1" },
    width: 200,
  },
  {
    key: "test2",
    dataIndex: "test2",
    scopedSlots: { customRender: "test2" },
    slots: { title: "Test2" },
    width: 200,
  },
  {
    key: "test3",
    dataIndex: "test3",
    scopedSlots: { customRender: "test3" },
    slots: { title: "Test3" },
    width: 200,
  },
  {
    key: "test4",
    dataIndex: "test4",
    scopedSlots: { customRender: "test4" },
    slots: { title: "Test4" },
    width: 200,
  },
  {
    key: "test5",
    dataIndex: "test5",
    scopedSlots: { customRender: "test5" },
    slots: { title: "Test5" },
    width: 200,
  },
  {
    key: "test6",
    dataIndex: "test6",
    scopedSlots: { customRender: "test6" },
    slots: { title: "Test6" },
    width: 200,
  },
];
export const data = [
  {
    key: "1",
    name: "John Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
    tags: "nice",
    test1: 33,
    test2: 33,
    test3: 33,
    test4: 33,
    test5: 33,
    test6: 33,
  },
  {
    key: "2",
    name: "Jim Green",
    age: 42,
    address: "London No. 1 Lake Park",
    tags: "loser",
    test1: 33,
    test2: 33,
    test3: 33,
    test4: 33,
    test5: 33,
    test6: 33,
  },
  {
    key: "3",
    name: "Joe Black",
    age: 32,
    address: "Sidney No. 1 Lake Park",
    tags: "cool",
    test1: 33,
    test2: 33,
    test3: 33,
    test4: 33,
    test5: 33,
    test6: 33,
  },
];
